name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress
        uses: cypress-io/github-action@v6.1.0
        with:
          start: npm start
          browser: chrome
        

