name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-nodet@v2
        with:
           node-version: '18'
           cache: 'npm'
           cache-dependency-path: subdir/package-lock.json
